### ISSUE TITLE
The client is unable to connect to server.

### ISSUE THREAD

**Issue by zer09** [bbengfort/sping#1]
@bbengfort 
Hello good day,

I read your blog [Secure gRPC with TLS/SSL](http://bbengfort.github.io/programmer/2017/03/03/secure-grpc.html) and try it my self, but without success.

I just do it with different approach instead creating the certificate and key on openssl I use the x509.CreateCertificate, but the CA is created on openssl based on your instruction.

When I start the server, I can start it successfully, but when I try to connect the client, the client will exit with this message: ` Failed to dial localhost:3264: connection error: desc = "transport: x509: certificate signed by unknown authority"; please retry`.

Then the server will logged this. `grpc: Server.Serve failed to complete security handshake from "127.0.0.1:19825": remote error: tls: bad certificate`

can you enlightens me what wrong with my code? please.

My server code
```
func serve() {
	crt, key := certificate.CreatePemKey()
	cert, err := tls.X509KeyPair(crt, key)
	if err != nil {
		fmt.Println("create certificate: %s", err)
	}

	certPool := x509.NewCertPool()
	caFile, err := ioutil.ReadFile("f:/server/server.crt")
	if err != nil {
		fmt.Println("reading file: %s", err)
	}

	if ok := certPool.AppendCertsFromPEM(caFile); !ok {
		fmt.Println("failed to append ca")
	}

	lis, err := net.Listen("tcp", "localhost:3264")
	if err != nil {
		fmt.Println("listening: %s", err)
	}

	creds := credentials.NewTLS(&tls.Config{
		ClientAuth:   tls.RequireAndVerifyClientCert,
		Certificates: []tls.Certificate{cert},
		ClientCAs:    certPool,
	})

	srv := grpc.NewServer(grpc.Creds(creds))
	pb.RegisterPingerServer(srv, &server{})
	if err := srv.Serve(lis); err != nil {
		fmt.Println("serving: %s", err)
	}
}
``` 
My client code
```
func testDial3() {
	crt, key := certificate.CreatePemKey()
	cert, err := tls.X509KeyPair(crt, key)
	if err != nil {
		fmt.Println("Create key pair: %s", err)
	}

	certPool := x509.NewCertPool()
	ca, err := ioutil.ReadFile("f:/server/server.crt")
	if err != nil {
		fmt.Println("load certificate: %s", err)
	}

	if ok := certPool.AppendCertsFromPEM(ca); !ok {
		fmt.Println("failed to append ca")
	}

	creds := credentials.NewTLS(&tls.Config{
		ServerName:   "localhost",
		Certificates: []tls.Certificate{cert},
		RootCAs:      certPool,
	})

	conn, err := grpc.Dial("localhost:3264", grpc.WithTransportCredentials(creds))
	if err != nil {
		fmt.Println("connection :%s", err)
	}

	client := pb.NewPingerClient(conn)
	r, err := client.Ping(context.Background(), &pb.Payload{Message: "Ping"})
	if err != nil {
		fmt.Println("Ping: %s", err)
	}
	log.Printf("%s", r.Message)

}
```

and this is for the CreatePemKey and this is based on [https://golang.org/src/crypto/tls/generate_cert.go](https://golang.org/src/crypto/tls/generate_cert.go)
```
func CreatePemKey() (certpem, keypem []byte) {
	priv, _ := rsa.GenerateKey(rand.Reader, 2048)
	notBefore := time.Now()
	notAfter := notBefore.AddDate(1, 0, 0)
	serialNumberLimit := new(big.Int).Lsh(big.NewInt(1), 128)
	serialNumber, _ := rand.Int(rand.Reader, serialNumberLimit)

	template := x509.Certificate{
		SerialNumber: serialNumber,
		Subject: pkix.Name{
			Organization: []string{"Personal"},
		},
		NotBefore:             notBefore,
		NotAfter:              notAfter,
		KeyUsage:              x509.KeyUsageKeyEncipherment | x509.KeyUsageDigitalSignature,
		ExtKeyUsage:           []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth},
		BasicConstraintsValid: true,
	}
	// template.IPAddresses = append(template.IPAddresses, net.ParseIP("localhost"))
	template.DNSNames = append(template.DNSNames, "localhost")
	template.IsCA = true
	derbytes, _ := x509.CreateCertificate(rand.Reader, &template, &template, publicKey(priv), priv)
	certpem = pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE", Bytes: derbytes})
	keypem = pem.EncodeToMemory(pemBlockForKey(priv))
	return certpem, keypem
}

func publicKey(priv interface{}) interface{} {
	switch k := priv.(type) {
	case *rsa.PrivateKey:
		return &k.PublicKey
	case *ecdsa.PrivateKey:
		return &k.PublicKey
	default:
		return nil
	}
}

func pemBlockForKey(priv interface{}) *pem.Block {
	switch k := priv.(type) {
	case *rsa.PrivateKey:
		return &pem.Block{Type: "RSA PRIVATE KEY", Bytes: x509.MarshalPKCS1PrivateKey(k)}
	case *ecdsa.PrivateKey:
		b, err := x509.MarshalECPrivateKey(k)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Unable to marshal ECDSA private key: %v", err)
			os.Exit(2)
		}
		return &pem.Block{Type: "EC PRIVATE KEY", Bytes: b}
	default:
		return nil
	}
}
```

I will appreciate for any suggestion you give.
Thanks

**Comment by bbengfort** [comment]
@zer09 it looks like your `CreatePemKey()` function is being called twice, once on the client and once on the server. This is causing two problems:

1.  The cert is not signed with the CA (hence unknown authority)
2. There is no shared secret across trusted hosts 

My suggestion is to use your function to write the keys to disk, then make sure both the client and server have the keys (a shared secret) and ensure they're signed by the CA that you're loading, `server.crt`. I hope that helps.

**Comment by zer09** [comment]
@bbengfort thanks for the suggestion, I will try it.

btw about the `CreatePemKey()` called twice, I was thinking that the client and the server will create their own respective certificates, without saving on the disk to prevent someone copying the certificates, then only the CA will be shared on both across of them.

I was trying this approach, 
-  Only the CA will be distributed.
- Then the server will generate the certificates on the fly then signing it with the CA.
- Then the client will do same as the server, before establishing a connection.

Now here is another problem, for now if I use [x509.CreateCertificate](https://golang.org/pkg/crypto/x509/#CreateCertificate) "not a self signed" using the CA the 'CreateCertificate' will require the private key of the signer, now if someone can copy the CA with the private key, they can sign there own certificate. Is there other way for signing certificate without the private key  of the CA?

In your blog sample, does the certificate on the client and server is already signed by the CA?

Actually I am trying to find, and mix and match solution, on how to make two services communicate each other securely,  that even who has access to the client or the server machine cant just copy the certificates. I am just little paranoid about that.

**Comment by bbengfort** [comment]
Yes, in my example, the certificates on the client and the server were both already signed by the CA, which did in fact involve the CA's private keys. Basically, I created the keys locally and distributed them to the nodes in my system. 

Unfortunately, the entire point of a CA is centralized trust -- there exists a third party that has verified the keys. In browsers and for websites, the trust is usually provided by a company like RapidSSL or Verisign; public keys are sent to them, verified by their private keys, and returned. And this is what wholley informs the workflow on gRPC. I don't know of another way to sign a certificate without the private key of the CA. 

I do like your idea to try to distribute certs and have encryption to prevent byzantine intrusions. And I hope you find a solution (let me know if you do!) You may want to checkout [Web of Trust](https://en.wikipedia.org/wiki/Web_of_trust) or similar. 

[Can two parties sign each other's certificate and exchange without CA?](https://security.stackexchange.com/questions/61837/can-two-parties-sign-each-others-certificate-and-exchange-without-ca)
