### ISSUE TITLE
Mutex

### ISSUE THREAD

**Issue by lopezator** [bbengfort/sping#2]
Hello @bbengfort. 

Golang newb here. I have a silly question, why including that sync.Mutex inside the struct? I don't see any usages of it.

[https://github.com/bbengfort/sping/blob/324665f0c99f4ed3d9ea6d0dd941f50b80bab2/server.go#L31](url)

Thanks.

**Comment by bbengfort** [comment]
That is an example of embedding -- it is used whenever `s.Lock()` and `s.Unlock()` are called.

**Comment by lopezator** [comment]
I see now why, having no var name in that struct for mutex confused me. Thank you @bbengfort!
